const express = require("express");
const { engine } = require("express-handlebars");
const dotenv = require('dotenv');
const path = require("path");
const routes = require("./routes/routes");
const app = express();
const db = require("./database/database");
const api = require("./api/api");
const port = process.env.PORT;
const cookieParser = require('cookie-parser');
const methodOverride = require('method-override');
dotenv.config();
app.use(cookieParser());
app.use(express.urlencoded({ extended: true }));
app.engine(".hbs", engine({ extname: ".hbs" }));
app.set("view engine", ".hbs");
app.use(methodOverride('_method'));
app.set("views", path.join(__dirname, "Resources\\views"));
app.use("*/css", express.static(path.join(__dirname, "public/css")));
app.use("*/js", express.static(path.join(__dirname, "public/js")));
app.use("*/img", express.static(path.join(__dirname, "public/img")));
app.use("*/fonts", express.static(path.join(__dirname, "public/fonts")));
routes(app);
api(app);
db.Connect();
app.listen(port, () => console.log(`${process.env.HOST}:${process.env.PORT}`));
